# Generated by Django 3.2.16 on 2022-12-06 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SitePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default='/', max_length=255, unique=True, verbose_name='url')),
                ('alias', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='ссылка')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='название')),
                ('intro_text', models.TextField(blank=True, default='', null=True, verbose_name='краткое содержание страницы')),
                ('content', models.TextField(blank=True, default='', null=True, verbose_name='содержание страницы')),
                ('pub_date', models.DateField(verbose_name='дата создания')),
                ('template', models.CharField(blank=True, default='.html', max_length=100, verbose_name='файл шаблона')),
                ('context_model', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='')),
                ('use_in_menu', models.BooleanField()),
                ('is_category', models.BooleanField()),
            ],
        ),
    ]
