# Generated by Django 3.2.16 on 2022-12-09 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitepage',
            name='context_model',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='контекст модели'),
        ),
    ]
