# Generated by Django 3.2.16 on 2022-12-14 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_sitepage_context_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitepage',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=255, unique=True, verbose_name='url'),
        ),
    ]
