# Generated by Django 3.2.16 on 2022-12-12 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_auto_20221210_0039'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'get_latest_by': 'pub_date'},
        ),
    ]
